name: FinSpect
services:
  Dbpostgres:
    # 1. Выбираем образ для нашего контейнера 
    image: postgres:latest
    
    # 2. Имя контейнера (опционально)
    container_name: postgre_db
    
    # 3. Переменные окружения
    # Они вообще не обязательны и их к примеру можно прописать 
    environment:
      POSTGRES_USER: postgre  # Имя пользователя
      POSTGRES_PASSWORD: postgre # Пароль
      POSTGRES_DB: FinSpect
    
    # 4. Порты.
    # Формат: "ПортНаХосте:ПортВнутриКонтейнера"
    # Стандартный порт PostgreSQL - 5432.
    ports:
      - "5432:5432"
        
    # 5. Тома (Volumes). САМОЕ ВАЖНОЕ!
    # Без этой строки все ваши данные удалятся, если вы остановите или удалите контейнер.
    # Мы привязываем виртуальный том 'pgdata' к папке внутри контейнера, где хранятся файлы БД.
    volumes:
      - pgdata:/var/lib/postgresql

# ОБЯЗАТЕЛЬНАЯ СЕКЦИЯ ДЛЯ ОБЪЯВЛЕНИЯ ТОМОВ
volumes:
  pgdata: