<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
      <UserSecretsId>126f20b5-9c0e-40b5-ad95-7384135a58d7</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Asp.Versioning.Mvc" Version="10.0.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\FinSpect.Infrastructure\FinSpect.Infrastructure.csproj" />
    </ItemGroup>

</Project>
